### ISSUE TITLE
shortcut key doesnt work after using it to open clipped

### ISSUE THREAD

**Issue by princeofguilty** [davidmhewitt/clipped#20]
super v is the shortcut key and once i use it to open clipped i cant type letter v again anywhere until a reboot is made, but the shortcut key stays working

**Comment by davidmhewitt** [comment]
Hi, thanks for the report.

I am unable to reproduce this issue, even using the same "super v" keyboard shortcut. Can you provide some more information that may assist in tracking down this issue?

For example, are you using elementary OS? Is it a standard PC keyboard? What keyboard layout are you using?

**Comment by bloopbytes** [comment]
Same problem in Juno.

**Comment by GammaGames** [comment]
Juno with standard keyboard layout, same problem.

**Comment by mtomov** [comment]
Yeah, same problem, Juno, all standard. In fact, any other key that you bind, after the first use, it becomes unusable.

**Comment by Julioevm** [comment]
Same here on Juno, used super + c and after a while c just stopped working. Had to close the process.
It didn't happen right after using it, I don't know what causes it exactly. 
Im using a laptop keyboard, with spanish keyboard layout.

**Comment by davidmhewitt** [comment]
Apologies for taking so long to get around to looking at this issue. I've never been able to reproduce it but some extra help from a user in #30 has helped me narrow it down.

I believe that this issue should now be fixed in the `master` branch and will look to release a new version in the next few days that includes the fix. If any of you are able to test it before then and confirm whether it does or doesn't fix the issue, that would be much appreciated.

**Comment by davidmhewitt** [comment]
Version 1.1.1 has been released to the AppCenter and I believe this includes a fix for the shortcut key only working once.

As such, I'm going to close this issue, but please feel free to re-open it or add another comment if you're still experiencing this particular issue after updating.

**Comment by GammaGames** [comment]
Thank you, I just installed it and tested it around some apps and haven't had any issues!

**Comment by GammaGames** [comment]
Hmm, I had it installed and after I logged in I couldn't use most of the super+letter shortcuts anymore, like opening the terminal. Uninstalling and re-logging fixed it, maybe it's not completely fixed?
